version: "3"
services:
  duck:
    image: docker.io/duckhq/duck:latest
    ports:
      - "8085:15825"
    volumes:
      - "./data:/data"
    container_name: duck
    command: ["start", "--config", "/data/duck.json"]
